spring:
  datasource:
    url: jdbc:h2:./data/test;MODE=MySQL;TRACE_LEVEL_SYSTEM_OUT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create
    open-in-view: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true